[project]
name = "flash-model-architectures"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.3",
    "parameterized>=0.9.0",
    "pre-commit>=4.3.0",
    "pybind11>=3.0.1",
    "pytest>=8.4.2",
    "torch>=2.8.0",
]
