[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "flash-model-architectures"
version = "0.1.0"
description = "A collection of high-performance model architectures."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.3",
    "pybind11>=3.0.1",
    "torch>=2.8.0",
    "tqdm>=4.67.1",
]

[project.optional-dependencies]
dev = [
    "parameterized>=0.9.0",
    "pre-commit>=4.3.0",
    "pytest>=8.4.2",
]

[tool.hatch.build.targets.wheel]
packages = ["fma"]
