[project]
name = "flash-model-architectures"
version = "0.1.0"
description = "Flash Model Architectures"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ninja>=1.13.0",
    "numpy>=2.2.6",
    "nvitop>=1.5.3",
    "pybind11>=3.0.1",
    "pyyaml>=6.0.3",
    "torch>=2.8.0",
    "tqdm>=4.67.1",
]

[dependency-groups]
dev = [
    "parameterized>=0.9.0",
    "pytest>=8.4.2",
]
