name: Style Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  style-check:
    name: Check Style
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: install dependencies
        run: |
          git submodule update --init --recursive
          python -m pip install --upgrade pip
          pip install isort black pre-commit

      - name: run formatting tests
        run: |
          pre-commit install
          make style
